// User auth action types
export const USER_REGISTER_REQUEST = "[USER] REGISTER REQUEST";
export const USER_REGISTER_SUCCESS = "[USER] REGISTER SUCCESS";
export const USER_REGISTER_FAILURE = "[USER] REGISTER FAILURE";

export const USER_LOGIN_REQUEST = "[USER] LOGIN REQUEST";
export const USER_LOGIN_SUCCESS = "[USER] LOGIN SUCCESS";
export const USER_LOGIN_FAILURE = "[USER] LOGIN FAILURE";

export const LOGIN_WITH_TOKEN_REQUEST = "[USER] LOGIN WITH TOKEN REQUEST";
export const LOGIN_WITH_TOKEN_SUCCESS = "[USER] LOGIN WITH TOKEN SUCCESS";
export const LOGIN_WITH_TOKEN_FAILURE = "[USER] LOGIN WITH TOKEN FAILURE";

export const USER_LOGOUT = "[USER] LOGOUT";

export const VERIFY_EMAIL_REQUEST = "[USER] VERIFY EMAIL REQUEST";
export const VERIFY_EMAIL_SUCCESS = "[USER] VERIFY EMAIL SUCCESS";
export const VERIFY_EMAIL_FAILURE = "[USER] VERIFY EMAIL FAILURE";

export const RESEND_EMAIL_REQUEST = "[USER] RESEND EMAIL REQUEST";
export const RESEND_EMAIL_SUCCESS = "[USER] RESEND EMAIL SUCCESS";
export const RESEND_EMAIL_FAILURE = "[USER] RESEND EMAIL FAILURE";

export const FORGOT_PASSWORD_EMAIL_REQUEST = "[USER] [FORGOT_PASSWORD] EMAIL_REQUEST";
export const FORGOT_PASSWORD_EMAIL_SUCCESS = "[USER] [FORGOT_PASSWORD] EMAIL_SUCCESS";
export const FORGOT_PASSWORD_EMAIL_FAILURE = "[USER] [FORGOT_PASSWORD] EMAIL_FAILURE";

export const RESET_PASSWORD_REQUEST = "[USER] RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "[USER] RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "[USER] RESET_PASSWORD_FAILURE";


// Order action types
export const CREATE_ORDER_REQUEST = "[ORDER] CREATE REQUEST";
export const CREATE_ORDER_SUCCESS = "[ORDER] CREATE SUCCESS";
export const CREATE_ORDER_FAILURE = "[ORDER] CREATE FAILURE";

export const GET_ORDER_LIST_REQUEST = "[ORDER] GET LIST REQUEST";
export const GET_ORDER_LIST_SUCCESS = "[ORDER] GET LIST SUCCESS";
export const GET_ORDER_LIST_FAILURE = "[ORDER] GET LIST FAILURE";